apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:uZ2QINqfqIz0xUi0ELFMRUGTkcJtZIa93g==,iv:qfSe5lOckThXpluRGOqiwj3h7Wo0nVzyu+zGlDl/coA=,tag:JUv3XRX157+sE9g5jF0j2g==,type:str]
sops:
    lastmodified: "2025-11-13T01:16:39Z"
    mac: ENC[AES256_GCM,data:ogYAaIM30ZVURg4kj8dtVUZi+SvdW024sxLWCPWHTn4gUIieGbeRAwapUHtrQb0F+8ErqYRcuPVZRSAHXfcNrjLk+TlWvrM0bhHkPIZVCap76PWfpXxq3/0iwF3CGvF1mGkoQsGyiJXdmpzPsSFYh3Kbyxo+DImH/c1iOoPw5zQ=,iv:cVYcOL5YLMylAaKT/o2RbtqAty/6IyLVsqqNUeWqEM8=,tag:/WjYrAZ03dfU+mCJxI16wg==,type:str]
    pgp:
        - created_at: "2025-11-13T01:16:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAyl9Tdmf2/6TAQv+OKLK5h6rPmdF34O63vZne9cHLYsX2lx+b5kXwFDHmbWO
            rkkf/uY423CRkmz2UCSNUCiYkSUgwECC7cOt4lWGKXK+1Iy9VAr15GO1QThuLii9
            KQe9xRKVcZlOpZo+eGJfdkp6hlgsINNgXyUh1L+x6o/+40zAyhx2ZrLvT5udj7Nr
            Ggj7LXE62d0iBK8X3aXocNkU9mHDz+F6gHOR2SRq8WQKBwqgDxlPypEyRBdJZoYg
            hha+VU+PWfk7NstNtmwQVnioksSs5pyqz8DkuDhqTv+a9UuI/D1zmKO7rNN0oY/B
            phhdmWAt+FC/8Tci9wNcEv0WV612CSmtx2zBXOZkQrqriAPzaZ3xrIBxEjtJ/m4u
            w6X44q9kK+VEhDhftd4f1UoJKtp8W+uR/1MD4N8ngRnBHBZcoFxPH4ygmYc+iDc2
            diAVs3FAtl1TTtVNRqtlGIGMfPr/uoCr42nYXkpXxv2YP3konOEZL57eCBTQ8CfP
            tr9tHjMiQOK2VO47+FOd1GYBCQIQOsvnL6k+KnlX070y2oN6oUbmGZc0/NtycwCu
            E0K8C3+SjS7mZP2xfW5Z53HT5U91x/gHzr5lqfAQoL9KwfWqTU/low+IEfGaTv9R
            THHD+Cs2u9mRn3PrncEVPsPesvGxCAs=
            =Ug7i
            -----END PGP MESSAGE-----
          fp: 6985870EBD0C2A623B4F1DD6162ED498FC2640FF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
